# Generated by Django 3.2 on 2021-04-19 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_accounts_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.location'),
        ),
    ]
