# Generated by Django 3.2 on 2021-04-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_accounts_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
