# Generated by Django 3.2 on 2021-04-20 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_accounts_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=225, unique=True)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('photo', models.ImageField(upload_to='product/')),
                ('sell', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('icon', models.ImageField(upload_to='category/')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField()),
                ('product_many', models.ManyToManyField(related_name='product_many_to_many', to='database.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.accounts')),
            ],
        ),
    ]
