# Generated by Django 3.2 on 2021-04-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='public_id',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
