# Generated by Django 3.2 on 2021-04-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_category_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='public_id',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updateAt',
            field=models.DateTimeField(null=True),
        ),
    ]
